### ISSUE TITLE
Return block not working

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Blocks#13]
Return block should return whatever you put inside.

You should put the return block at the end of a function that returns a number, text or boolean, and it returns it.

It just sits there running forever and ever.

Whenever you run the return block, it just keeps running forever and ever, stopping all functions that use it and all scripts that have those functions.

Just click the block or put it in a function.

You scroll down to the custom blocks tab, click the return block, and it just sits there forever running. I dove into the source code, and I couldn't find a reason it would do this.

Google Crome, Microsoft Edge. Versions Uknown, just the most recent.

**Comment by RedMan13** [comment]
return doesnt work on script click
you need to run the inline/custom block as a whole and not instead run the code blocks contained inside

**Comment by RedMan13** [comment]
+its not running forever, script click requires the code to state it has stopped but return never does this as it expects to be closing a called function and not a script block

**Comment by ghost** [comment]
ok, thank you
