### ISSUE TITLE
inline block missing functionality

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Blocks#14]
The inline block is a block that you can put instead of a function that returns a number, however stacking multiple inline blocks at a time lead to some bugs.

You can very easily drag out an inline block and put it in your code, then put another inline block INSIDE of the return block on the previous inline block, and this works very well, however when you duplicate it and try to stack BOTH of them AT THE SAME TIME, it doesn't work. You have to do it one at a time.

While this would be very useless in a normal coding scenario, it's fun for people who just like to mess around :D

**Comment by RedMan13** [comment]
oh yeah, i think this is the same issue that makes it such a pain to construct switch case statements sometimes

**Comment by JeremyGamer13** [comment]
does this work if you drag the center of the inline block? not sure if im understanding fully
![image](https://github.com/PenguinMod/PenguinMod-Blocks/assets/69337718/1e29498b-ca29-41c2-8324-d68ac9f7d2ab)

**Comment by RedMan13** [comment]
@JeremyGamer13 if im understanding him correctly its the same/similar issue with the case block not wanting to insert if they dont have the c-clamp filled in and being really buggy about wrapping around blocks

**Comment by ghost** [comment]
![block_5_15_2024-3_52_11 PM](https://github.com/PenguinMod/PenguinMod-Blocks/assets/169567295/9fa42b8a-bcdc-47b8-9684-531b12559c11)

to make something like this, you have to drag it one at a time because if you duplicate the whole thing and drag it in to the return, it wont work, although i don't see how fixing this would be helpful for making an actual game :p

**Comment by ghost** [comment]
![image](https://github.com/PenguinMod/PenguinMod-Blocks/assets/169567295/009f195b-3d76-45b8-a446-1511e77149e4)

it wont let me drag it in

**Comment by RedMan13** [comment]
if you could include your hardware specs cause i just did it and it works :bleh

**Comment by RedMan13** [comment]
nvm im doing ti differently

**Comment by RedMan13** [comment]
you have to drag the block to center on the input

**Comment by RedMan13** [comment]
leik thias
[Screen recording 2024-05-15 1.57.46 PM.webm](https://github.com/PenguinMod/PenguinMod-Blocks/assets/74981904/3783ac75-4392-4777-9c3c-9cbe0de51c4b)

**Comment by RedMan13** [comment]
and to be clear this is a function of dragging a block into an input and has nothing to do with it being an inline block
its just easier to do with inline blocks since they have content stacked vertically rather then horrizontally

example of this being the case on more normal blocks 
[Screen recording 2024-05-15 2.02.29 PM.webm](https://github.com/PenguinMod/PenguinMod-Blocks/assets/74981904/b492ccbe-44f8-41ae-80c0-a9a2faf90519)

**Comment by ghost** [comment]
OOOOHHHHH

i guess i only tested the inline block lol

![image](https://github.com/PenguinMod/PenguinMod-Blocks/assets/169567295/1b4b6d95-e1f3-4e11-905c-cd5871c7db77)
thx

**Comment by dashound9** [comment]
he he :D

<img width="1788" height="892" alt="Image" src="https://github.com/user-attachments/assets/5c053557-97d8-4661-afe3-4e13d729217a" />
