### ISSUE TITLE
Not enough updates

### ISSUE THREAD

**Issue by ghost** [PenguinMod/PenguinMod-Blocks#15]
there should be more updates
but theres not

i need to look at code

UPDATE PLEEAAAAASSEEE!!!!!!

thx

**Comment by RedMan13** [comment]
ecus me hwart

**Comment by Ianyourgod** [comment]
…

**Comment by PuzzlingGGG** [comment]
wait till bro finds out about extensions

**Comment by Ianyourgod** [comment]
and the fact that we’re actively working on stuff
