### ISSUE TITLE
PM Text Render Memory Issue

### ISSUE THREAD

**Issue by LeafiDev** [PenguinMod/PenguinMod-Blocks#19]
### Expected Behavior

clones should render text normally for a trail on text

### Actual Behavior

text is rendered very pixelated and sometimes doesn't render, or it crashes the editor.
**(will happen at clone creation if a provide **"wait () seconds"** block is less than 0.1)**

error text provides: "Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Out of memory at ImageData creation."
This will only happen in fullscreen.

### Steps to Reproduce

Mainly used when using clones in quick succession
It has started to do this since specifically yesterday.
https://github.com/user-attachments/assets/91ea1491-b9e5-4adc-8b6b-de799

### Operating System and Browser

Windows 11, Chrome Version 131.0.6778.140 (Official Build) (64-bit)

**Comment by LeafiDev** [comment]
https://github.com/user-attachments/assets/199d0ece-95e2-4130-8b2e-91ae02ebea96

**Comment by RedMan13** [comment]
sir this is a system failure on your end

**Comment by LeafiDev** [comment]
I was starting to think so. Thx
