### ISSUE TITLE
[Enhancement] Add a dropdown option for custom blocks

### ISSUE THREAD

**Issue by fo-od** [PenguinMod/PenguinMod-Blocks#5]
This would be very helpful for creating a custom block that has a value that only needs to be selected from a set list of texts, instead of trying to remember a lot (and possibly misspelling) of values.

pls add !!!!!
(if there is an extension that adds this tell me because i cant find one)

**Comment by Ianyourgod** [comment]
This has been suggested before, we would like to add this, it would be hard

**Comment by fo-od** [comment]
oh i didnt know this had been suggested before, sorry for the duplicate
nice to know that you are thinking about it though!

**Comment by SharkPool-SP** [comment]
My Blocks+ accomplishes this. Custom dropdowns can be made with "dropdown maker" from my gallery
