### ISSUE TITLE
[Help] PenguinMod Blocks Having Issues When Used in Snail IDE

### ISSUE THREAD

**Issue by nmsderp** [PenguinMod/PenguinMod-Blocks#9]
### Expected Behavior

Lists should appear in Snail IDE

### Actual Behavior

Lists do not appear

### Explanation
Hello, I am the lead developer for a penguinmod mod called snail ide. Most of the time I have my own repositories for certain parts of Snail IDE, however for the blocks I use penguinmod's. For some reason lists have randomly disappeared from Snail IDE. Do you have any idea what is happening.
[This](https://github.com/Snail-IDE/snail-ide.github.io) is my GUI repo

**Comment by Ianyourgod** [comment]
snail ide :skull:

**Comment by Ianyourgod** [comment]
this is because we merged an addon

**Comment by Ianyourgod** [comment]
prob

**Comment by Ianyourgod** [comment]
gsa get your ass over here

**Comment by JeremyGamer13** [comment]
you need to merge some changes we made to lists, if i can find the changed repositories before godslayerakp messages then ill send them here

**Comment by nmsderp** [comment]
i fixed it
